[theme]
base = "dark"  # "light" or "dark"
primaryColor = "0040A8"  # primary accent color

# Background color for the main content area.
# backgroundColor = "EFEF33"

# Background color used for the sidebar and most interactive widgets.
# secondaryBackgroundColor = "89E3FF"

# Color used for almost all text.
# textColor = "red"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
# font =
